import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Bridge3Academy Admin Page",
  description: "Generated by Bridge3Academy",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="border-b border-border bg-card">
          <div className="mx-auto flex w-full max-w-6xl items-center justify-between px-6 py-4">
            <Link href="/" className="text-sm font-semibold">
              Bridge3Academy Admin
            </Link>

            <nav className="flex items-center gap-2 text-sm">
              <Link href="/" className="rounded-md px-3 py-2 hover:bg-muted">
                Home
              </Link>
              <Link
                href="/waitlist"
                className="rounded-md px-3 py-2 hover:bg-muted"
              >
                Waitlist
              </Link>
              <Link
                href="/tasks"
                className="rounded-md px-3 py-2 hover:bg-muted"
              >
                Tasks
              </Link>
            </nav>
          </div>
        </header>

        {children}
      </body>
    </html>
  );
}
